name: Docker Image CI

on:
  push:
    branches: [ "master", "githubActionTesting" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: Sancus-Discord.NET
      run: docker build . --file Dockerfile --tag Sancus-Discord:$(date +%s)
